### ISSUE TITLE
Apple Watch support?

### ISSUE THREAD

**Issue by idleberg** [artginzburg/sudo-touchid#10]
I was somewhat expecting, that the Apple Watch uses the same API as Touch ID, but it doesn't seem to be the case. So, I was wondering if double-tapping the Apple Watch's button could be added in a future version. Or do you see this feature request out of scope for your project?

**Comment by artginzburg** [comment]
Currently, you may try [biscuitehh/pam-watchid](https://github.com/biscuitehh/pam-watchid).

About adding this as a feature — I think `sudo-touchid` is supposed to be native and reliable. Custom PAM plugins seem to be out of this scope due to security concerns and differentiating installation requirements.
(This is why I'm just leaving links to such projects/methods in Readme)

However, 3rd-party PAM plugins are used by developers anyway. So collecting, maintaining, and automatizing them sounds useful. There's definitely a room for extended self-contained solutions here.
