### ISSUE TITLE
TouchID not prompted when running sudo in tmux

### ISSUE THREAD

**Issue by cedrickring** [artginzburg/sudo-touchid#6]
As the title says, inside tmux I'm still prompted with `Password: ` instead of having the TouchID window show up.

**Comment by artginzburg** [comment]
Sounds logical in terms of security. Anyway, I tried some things and got tmux to stop asking for sudo password by running `sudo tmux` instead of just `tmux` initially.

That actually displays the TouchID window. The downside is that anything that is run inside a `sudo tmux` session has super-user access without any prompt. Not so good, but someone (like myself) may find it useful.

**Comment by orgcontrib** [comment]
You may want to have a look at [pam_reattach](https://github.com/fabianishere/pam_reattach) plugin.
